name: Save Command

on:
  repository_dispatch:
    types: [save-command]

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update history
        run: |
          FILE=docs/history.json
          TIMESTAMP=$(date -Iseconds)

          jq ". += [{\"timestamp\":\"$TIMESTAMP\",\"command\":\"${{ github.event.client_payload.command }}\"}]" $FILE > tmp.json
          mv tmp.json $FILE

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/history.json
          git commit -m "Add command"
          git push
