name: Save Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Command to save"
        required: true

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update history
        run: |
          FILE=history.json
          TIMESTAMP=$(date -Iseconds)

          jq ". += [{\"timestamp\":\"$TIMESTAMP\",\"command\":\"${{ github.event.inputs.command }}\"}]" $FILE > tmp.json
          mv tmp.json $FILE

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add history.json
          git commit -m "Add command"
          git push
